### ISSUE TITLE
Tests fail when using Broadcast receiver

### ISSUE THREAD

**Issue by hatepoint** [hatepoint/phrases-hyperskill-tests#11]
Can you please check the latest commit in dev/stage3? I didn't figure out how to add the support for notifications + broadcasts
Other tests seem to work fine

Thanks @RedJocker

**Comment by RedJocker** [comment]
Is the solution on dev/stage3 the one you intend to test?
I don't see a broadcast receiver on there.

**Comment by RedJocker** [comment]
Are you able to load user submissions from hyperstudio?
Because the last report tried solving stopwatch project with use of AlarmManager+BroadcastReceiver and at first it didn't work, but then I wrote that method ```supportForAlarmManager``` and was able make assertions as expected.

Another thing, I'm not sure that you are aware that tests can control passage of time with shadowLooper.idleFor(timeAmount, TimeUnit.THE_UNIT_YOU_LIKE). Probably to trigger alarm you have to schedule a time in the future and advance the clock to be after that time

**Comment by hatepoint** [comment]
I've never used hyperstudio before. Can you send me a link?

**Comment by RedJocker** [comment]
If you have permissions it appears a button with a purple H and a notepad on stages of a project together with some other buttons with admin links.
for stopwatch stage5 would be this https://studio.hyperskill.org/login?next=/steps/9290/submissions, but you need permission.

----

I think it is easier to include here the solution that uses AlarmManager + BroadcastReceiver and I will take a look on it.
I have finished other tasks I was doing and alexandra asked me to give priority to this project so no need to be struggling with test just send me the troubles and I can try make them work

**Comment by hatepoint** [comment]
The solution is on the dev/stage3 branch. Receiver: https://github.com/hatepoint/phrases-hyperskill-tests/blob/dev/stage3/Phrases/stage3/src/main/java/org/hyperskill/phrases/Notification.kt
AlarmManager (that one scheduleNotification method that is marked with /* */): https://github.com/hatepoint/phrases-hyperskill-tests/blob/dev/stage3/Phrases/stage3/src/main/java/org/hyperskill/phrases/MainActivity.kt

**Comment by RedJocker** [comment]
Ok, I think I found the problem. Robolectric uses emulated time, but time libraries like Calendar are not shadowed by robolectric and return the actual computer time instead of the emulated time that begins at 1970-01-01 00:00 +/- timezone.
And because of this supportForAlarmManager is never triggering intents, since there is a time comparation there happening with trigger time on today and SystemClock in beggining of 1970. 

I think It is possible to have a  @Before setup method to set the emulated time so that it syncs with computer time.
I will keep testing things here how to handle this.

**Comment by RedJocker** [comment]
sent a pull request, now the test is failing because of notification title, but the notification is being sent though broadcast receiver
